### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by desugar-64** [gotokatsuya/ParkedTextView#1]
Hi. Can I set parkedHint before text but not after like in example?
For example I want to use it like country phone code holder: +1(is parkedHint) 0000000(editable number).

**Comment by gotokatsuya** [comment]
Hi @sergeyfitis .

Sorry, ParkedTextView can not write like it.

But, it is so interesting. 

I'm going to implement this function on next version.

Thank you.

**Comment by desugar-64** [comment]
Alright. Thank you :+1:

**Comment by varun-manjunath** [comment]
@sergeyfitis [Check out this recent thread with a solution for your case](https://github.com/gotokatsuya/ParkedTextView/issues/3#issuecomment-508956114) (4 years too late huh?  xD)

**Comment by desugar-64** [comment]
@varun-manjunath Thanks man xD

**Comment by desugar-64** [comment]
Better late than never.
